### PR TITLE
Do not confuse an empty message with a closed connection

### LINKED ISSUE #312: WebSocket message with empty payload misinterpreted as close message
As of commit 8a697622495fd319582cd1c604e7eb2cc0ac0ef6, a WebSocket message with payload length zero causes the connection to be closed (“Client closed connection”). This seems to be inconsistent with the specification and with the previous behavior of websockify.

### PR DESCRIPTION
**Pull request by andersk**
Fixes #312.

### CODE REVIEW

**Comment by CendioOssman** [comment]
Argh. I was trying to make it match the behaviour of `Socket` as much as possible. But you are right, WebSockets are message oriented.

However, we have both `recv()` and `recvmsg()`. Perhaps only `recvmsg()` should be changed to return `None`? That would keep the API more familiar for those using things as a normal socket, and still allow full functionality for those who try to do message based communication?

**Comment by andersk** [comment]
We could filter out empty messages from `recv`, so that it can use the empty string unambiguously for the closed case:

```python
    def recv(self):
        msg = self.recvmsg()
        while msg == '':
            msg = self.recvmsg()
        return '' if msg is None else msg
```

But then we also need two versions of `pending`, one that checks whether messages are available for use with `recvmsg`, and one that checks whether _nonempty_ messages are available for use with `recv`.

**Comment by CendioOssman** [comment]
You are right, the rabbit hole just goes on. And since we have `pending()` we're already different from normal `Socket`s anyway. So let's go with your initial plan of `None` everywhere.

However, to avoid surprising people, could you update the docstring for `recv()` to mention that the message oriented nature of WebSockets could result in getting an empty buffer?

**Comment by andersk** [comment]
Sure, how’s this?

**Comment by CendioOssman** [comment]
Great, thanks. :)

**Pull request merged**
