### PR TITLE
When using the --verbose option set root log level to DEBUG

### PR DESCRIPTION
**Pull request by javicacheiro**
When using the --verbose/-v option set root log level to DEBUG

### CODE REVIEW

**Comment by samhed** [comment]
:thinking: is this common practice?

**Comment by javicacheiro** [comment]
It depends on the external modules that you use and how verbose they are.

In the case of websockify it does not increase the logging messages much and it is quite useful for debugging so I think it is quite convenient and it has no obvious drawbacks.

**Comment by CendioOssman** [comment]
We seem to have already crossed the bridge of mixing up "debug" and "verbose", so that should not be a blocker here.

But I'm confused about what this PR actually does. What log messages are appearing at different levels of the hierarchy?

**Comment by javicacheiro** [comment]
Sorry, I forgot to include in the previous comment the output we would get without the "--verbose" option:
```
TokenRedis backend initilized (3.3.3.3:6379)
WebSocket server settings:
  - Listen on 1.1.1.1:9444
  - Web server. Web root: /root/websockify/standalone/novnc/noVNC-1.3.0
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from 1.1.1.1:9444 to targets generated by TokenRedis
Resolving token 'TKNXXXX'
2.2.2.2 - - [16/May/2022 17:40:52] 2.2.2.2: SSL/TLS (wss://) WebSocket connection
2.2.2.2 - - [16/May/2022 17:40:52] 2.2.2.2: Path: '/websockify?token=TKNXXXX'
2.2.2.2 - - [16/May/2022 17:40:52] connecting to: 4.4.4.4:5901
```

**Review by samhed — APPROVED** [review]
Looks good to me

**Pull request merged**
