### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by javicacheiro**
Adding support to run with docker/podman or any other compatible container runtime.

To simplify the upgrades, the container is built on the official python image, in this case python:3.6 but it would be very easy to move to a different python version.

The container is built using the latest official release. To generate the Dockerfile for a new release is as simple as to bump the VERSION variable.

I also kept the same dependencies as currently used in the CI process: numpy<1.17 redis simplejson jwcrypto.

Finally, the users can provide files using the standard /data volume (certificates, novnc).

If you create a dockerhub account, let's say it is named `novnc` then you can build the image with:
```
docker build -t novnc/websockify:0.10.0 .
docker push novnc/websockify:0.10.0
```

And then you can just update the README to point there, in the meanwhile I think it is useful to have the image accessible so users don't need to build it themselves again (since this precisely the main advantadge of using docker).

### CODE REVIEW

**Comment by CendioOssman** [comment]
The other PR doesn't seem to resume, so let's go ahead here.

Your PR looks mostly fine. But it has the same issue as the other one; that it refers to an external repo. Please adjust the instructions so that shows how to get going with a local copy of websockify. The issue of having it in some repository is best dealt with separately.

**Comment by javicacheiro** [comment]
Changed so now the image is build locally and there is no dependency on an external repo.

For convenience the name of the locally build image is "novnc/websockify" (you can name a locally built image as you want), so in the future when the project has a dockerhub account it would be just a matter of removing the docker build line from the instructions.

BTW, if you need help setting up the dockerhub repository and uploading the images just let me know.

**Review by CendioOssman — APPROVED** [review]
Nice, thanks!

The repo issue is more one of having yet another thing to keep track of and maintaining. Having it like this allows us to keep it a bit more "best effort" than having some CI job failing.

**Comment by OliverEvans96** [comment]
Are there plans to publish the official image to dockerhub?

**Comment by CendioOssman** [comment]
Not at the moment. I don't think anyone is opposed to it, but it's a bit of effort setting everything up.

**Pull request merged**
