### PR TITLE
Use GitHub's recommended .gitignore file for Python projects

### PR DESCRIPTION
**Pull request by vuzdemav**
Taken from https://github.com/github/gitignore/blob/master/Python.gitignore

### CODE REVIEW

**Comment by vuzdemav** [comment]
Actually all I wanted for myself was to add the `build/` and `dist/` directories created by `setup.py`, but I thought it is a good idea to use this template in case it is useful for others.

**Comment by samhed** [comment]
I'm not sure I understand the purpose of having a generic .gitignore like that? I'd prefer to have a specific one for each project, to avoid confusions.

**Comment by CendioOssman** [comment]
Yeah, I agree. This seems wildly excessive for our small project.

@vuzdemav, please adjust this PR with just the things that you were seeing and we'll add those.

**Comment by vuzdemav** [comment]
I updated so that now it only adds `build/` and `dist/`

**Pull request merged**
